### ISSUE TITLE
Realm data is not shown when using react-native-threads

### ISSUE THREAD

**Issue by SMhdAsadi** [panz3r/react-native-flipper-databases#294]
**Describe the bug**
I have a project which uses react-native-threads. This package creates another JS process. I need to work with database in this new process. Everything is working fine regarding this library.

Flipper connects to this newly created process successfully and default plugins are working fine. But there is an issue for Database plugin. It correctly shows the database, tables and schemas, but no data is shown. When I hit the refresh button, a new warning is shown in the console. This is the warning:

![image](https://user-images.githubusercontent.com/63557556/158319542-220a9a50-6c80-4011-9381-f4b381cb1c2f.png)

I suspect there is a problem with react-native-threads and this plugin.
Thanks in advance.

**To Reproduce**
1. Create a new React Native project
2. Add react-native-threads to the project and create a thread
3. Use Realm in newly created thread
4. Try to use Database plugin in Flipper for this project

**Expected behavior**
I Expect to see the content of tables.

**Screenshots**

![image](https://user-images.githubusercontent.com/63557556/158320404-0ed35628-9339-4d37-867f-e1f5d1e893d6.png)

**Smartphone**

- Device: Samsung Galaxy A10s
- OS: Android 11
- Version 2.2.1

**Additional context**

**Comment by panz3r** [comment]
Hi @SMhdAsadi ,
Thanks for your feedback.

I tried replicating your issue inside the `WatermelonDB` example app contained in this repository but I'm having issues as soon as I integrate `react-native-threads` and I suppose this is because of incompatibility with the latest RN versions.

Can you please share a testable example of your issue?

Also a quick question about your implementation, are you accessing the `RealmDB` instance only from the worker thread or also from your main thread? Because in the latter case you should attach the `react-native-flipper-database` driver only to the instance open on the main thread and should be able to access the saved data.

**Comment by SMhdAsadi** [comment]
Thanks for your response.
Yes I'm accessing RealmDB instance only from the worker thread.

Surprisingly the issue is fixed. I didn't change anything in my code, just did a restart on my machine and it works.

**Comment by Rishana-Rabiya** [comment]
I am not able to use realm db inside the newly created process. How did you managed to do that?
